source "https://rubygems.org"

ruby "3.4.4"

# Rails 本体
gem "rails", "~> 7.1.3"

# データベース: PostgreSQL
gem "pg", "~> 1.1"

# Web サーバー
gem "puma", ">= 5.0"

# OS依存で必要になる場合がある
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

# 起動高速化
gem "bootsnap", require: false

# ページング
gem "kaminari", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mingw x64_mingw ]
  gem "rspec-rails"       # テストフレームワーク
  gem "factory_bot_rails" # テストデータ生成
end

group :development do
  # gem "spring" # Rails起動高速化（必要なら有効化）
  gem "rubocop", require: false   # Linter（任意）
end

group :production do
  # Redis や rack-cors を使うならここで追加
  # gem "redis", ">= 4.0.1"
  # gem "rack-cors"
end
